apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec: 
  acme:  #automated certificate management environment
    server: https://acme-v02.api.letsencrypt.org/directory
    email: negpoze1@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers: 
      - http01:
          ingress:
            class: nginx
